### ISSUE TITLE
How JNode works and how to create OSes in Java like that?

### ISSUE THREAD

**Issue by Ambijubi** [jnode-revisited/jnode#17]
Maybe this is an offtopic, but I VERY want to know it.
I want to create my own OS like MS-DOS, that brings a little nostalgia, but have some modern features in Java (I know Java and learning C++).
But I can't find any good tutorials how to make operating systems in Java, and probably most accessible operating system in Java that i found is JNode.
This is very good OS, but I didn't find explanations how it works.
Tell me, please, How it works and how to create operating systems in Java?

**Comment by tripleo1** [comment]
Do some research and document what you find, knowing that much of it will be either wrong or misinformed.  You are welcome to ask more specific questions here.

> This is very good OS

This is an interesting statement.
